#!/bin/sh

TOMCAT_HOME=/usr/local/lib/tomcat6
USER=tomcat6

if [ -z "$(getent passwd $USER)" ]; then
  echo "creating the user and group '$USER'"
  sudo adduser --system --group $USER
  sudo adduser $USER sudo
fi
